server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Miven666/SpringCloudLearningConfig
          search-paths:
          username:
          password:
      label: master
    # 消息总线
    bus:
      enabled: true
      trace:
        enabled: true
  # rabbitmq
  rabbitmq:
    host: 192.168.135.128
    port: 5672
    username: admin
    password: admin


# 服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh