# spring
spring:
  profiles:
    active: one
  application:
    name: eureka-server
# eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false